apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: mongodb
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017