apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  root-username: {{ .Values.mongodb.rootUsername | b64enc }}
  root-password: {{ .Values.mongodb.rootPassword | b64enc }}
  user-username: {{ .Values.mongodb.user.username | b64enc }}
  user-password: {{ .Values.mongodb.user.password | b64enc }}