apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.js: |
    db.createUser({
      user: 'videoCallUser',
      pwd: 'password',
      roles: [{ role: 'readWrite', db: 'videoCallDB' }]
    });
    db.createCollection("calls");