apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  root-username: cm9vdA==  # 'root' в base64
  root-password: cGFzc3dvcmQ=  # 'password' в base64
  user-username: dmlkZW9DYWxsVXNlcg==  # 'videoCallUser' в base64
  user-password: cGFzc3dvcmQ=  # 'password' в base64