mongodb:
  image: mongo:latest
  rootUsername: root
  rootPassword: password
  database: videoCallDB
  user:
    username: videoCallUser
    password: password

server:
  image: k3d-registry:5005/server:latest
  port: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

client:
  image: k3d-registry:5005/client:latest
  port: 3000
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

persistence:
  enabled: true
  storageClass: "local-path"
  size: 1Gi

certs:
  server:
    crt: |
      -----BEGIN CERTIFICATE-----
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lVTjZEMlhtTmVpMStGb2xsUW8zb3VUeDV2VUtJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TkRFd01EWXhNVFV3TXpsYUZ3MHlOVEV3Ck1EWXhNVFV3TXpsYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzVWZVlqWjFrUzZqT3NjUEN6NW1vYUszRlB4SUVuK1hLNGNPcmFHaGp5Cko2ZjZKN0UybUVGSWhsUnRSYVJLY3JwaGRoVEJBRDRSQXZubElhemw3OTBjbmhqVWhsUzdFaTUyVGdRSlVSWmoKWlowREZUWEh2QnhVanVSWXdtZFhkU2Z0QmNFNHFIUThxS3M2ekVCeTBWTENQbjlQT2ZaV0VJcTJBVFlwVktyYwo3ZWVycXJtN2NZQ3o4UVVnMFk5bVNFRG1hbkhORGR2bkRxdEYxcmVsQkJranpiVDBSMEpUakNkQ1Q0UUdIaDhsClJVaml0SDNSZFhSNEVtbDFacGlGQ0Z1SkVJNEc1VjE3bGFId1ptYXZTQ0FPck5NUWJxeDZTYVlYZnp1VHJMQXIKMm5XVjZ5OTNTa3dJc1NFZnJZU0c4ajl6enFpc2RnQXcrV2NSTnRrWW1QZi9BZ01CQUFHalV6QlJNQjBHQTFVZApEZ1FXQkJSNXRXclorWFB5RmZ0cTBzVEEreXFVZzhCdEt6QWZCZ05WSFNNRUdEQVdnQlI1dFdyWitYUHlGZnRxCjBzVEEreXFVZzhCdEt6QVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUMKZUd2TWx4WlBSN0s4UkdldnZ0YWtxZ2JwTDgvMUQ1Nm05UHJSQ1lZeEw5YzNNa3FvaEhmNnllczNHa1ZhemJjOApSU21tWXRNNGp1bW1xbWtZaDZ3MVNXc2VoTGEvS1RQWjhHK0F6cjV5b3dHRWdQMTZZZkx1Nm1SOWdUR3FscUVnCnNzL2xnUDJPYzlMcXJNeGJabDlKM3k0RlFadG1WWWU0TTZIb2xZYStOWkoycVVxQlJZQ255UUNycU0vRVdtTEoKa1U1RjBLTlFPb0pwN0ZXckRsZkVuQS9LUkt0dmhJQXcreE5TWlZpbk55WEdPOFFkbUsvaXBGWXlQdVlzRW1JMwpYS2xvb0d6aDgxWWNxeHM0NFo3M2QzNCtBMkRTNU9FdWJ6WjZjNWpqd3BJbDRUbW4vdzRYYi94VzZBYlh5NHcxCm5zMGgxNGFISjZBZWJRWHdVcDFoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      -----END CERTIFICATE-----
  key: |
      -----BEGIN PRIVATE KEY-----
      LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzVWZVlqWjFrUzZqT3MKY1BDejVtb2FLM0ZQeElFbitYSzRjT3JhR2hqeUo2ZjZKN0UybUVGSWhsUnRSYVJLY3JwaGRoVEJBRDRSQXZubApJYXpsNzkwY25oalVobFM3RWk1MlRnUUpVUlpqWlowREZUWEh2QnhVanVSWXdtZFhkU2Z0QmNFNHFIUThxS3M2CnpFQnkwVkxDUG45UE9mWldFSXEyQVRZcFZLcmM3ZWVycXJtN2NZQ3o4UVVnMFk5bVNFRG1hbkhORGR2bkRxdEYKMXJlbEJCa2p6YlQwUjBKVGpDZENUNFFHSGg4bFJVaml0SDNSZFhSNEVtbDFacGlGQ0Z1SkVJNEc1VjE3bGFIdwpabWF2U0NBT3JOTVFicXg2U2FZWGZ6dVRyTEFyMm5XVjZ5OTNTa3dJc1NFZnJZU0c4ajl6enFpc2RnQXcrV2NSCk50a1ltUGYvQWdNQkFBRUNnZ0VBQmpaZXlpYVNJNnp6S09vSHpNL3pvazU4N1JSWnRxQlFReDhmbm1iV3ArU2wKOVZqR0pjK1BtbXhvOHZXZSt5OXRGN2NFSFJPZFZsSXlxWWFOanpuS0ZYN3V0MEFheklvTEpWSjlzd2pxZE41RApOQlZjczVSQmFDOVB4Ymx4SnVlcmJmRFZHOGxxb2tFQU8zWEVKWC9LRWtRYVFYalNQckpLSkFNQlJoaTVxN00yCmttdHQ1MVFnZGxnNkJzcHFnSmtJeFZ1cjJiVDBlWnBBZitxZG1obHkyMDBJSUkxWm45eWZ3TEdseERHRWdxb1cKcUhYVmlkL1NrYzRGdlNBWkl5Nnh5SER0WlhRQkpxaFRVTnA3NVhzWGRySlhHeXRidE85VWtpV0NDVThmR1l6SQpDeGdXM0wzeGpBRFdLMHBEMEcwdU84VW1xRjIyS3VJUmVBZHBZZ2U4SVFLQmdRRC9Dc2dLQTBzRDRCelJjbmhuCmpxdjZzVTBnT1dKM3phQXcrUWcxR0k1YjBtb051d09uckRwK0FwQUVxb0RJeXZoamZmQnEyclNpRW1YdUpERjUKZkJjTzBDeE5FUTJkK3Q1TjNaZ0JXY3FQN29UaGkwZGc2amVpMU8wUUt0TzkzL3haRmo5cU9pcFpXM3lJM3BVWQpoMnQwcUpFM21HYjN3QXhDT0lrZk1KNzUwUUtCZ1FDNkNCaU5aVlJwM2psSTFpTnpjZ3ZvOWMrTmt1Yi9IWnRZCk1Ba0FabXpNSWs4NUI5eld6L2swWjkzc2psMVVha2xTMkpVZnN6bU5MaXhjTDNIS3dzaFpNRVQ3dFNIbzlySnAKUXdreWR0OWF6YTkrN3ZPT0w2M2djRHIwWnBvWmlyN0krK2d4THFIbTM3eVZTWTFFaXJ2ZUs1VC84T01XMG5OMwpqRzFqM1lONHp3S0JnUURPdzJQWFVrSWZtekpoenVhME5lTlJNeXB1eEhjQzMwNU9SYWFVdlJxMGNFcVFaUndhCmRETmJjeUprMWdIZ1IwVEdEQlM3M0NEeS8rMW8raWl0NzU4VjRFajZGYWd2ZW5GOU9QZ0JxRlRqQ1NEclpTbngKOVJBenoyRjlhT3NPbFNjVTVrZDFERURHL3JkZ2t1clczdnFMc2hsQXRDcE9Fb0Vkc28zZ0hsL1Q4UUtCZ0JTRwpsaWJydWorZ0hGUDBCSjlWUXdrbUxndGgzUWppL0dQamtPcXhZbW0zazJRb2dPNVdyaGxoS0hSVVZPbmVmRTZlCnhQMWxhZ0V3eWdZMTJlbFVTb1RFdGFmTUdYeTUwMytYdk9rTGdxTmpOR3pkOHBPS29UVzFURnZ4QWltMVRFMmkKdGNEUGMxK2s2Z3JTdmJxRlVDczRSYzFqaDdyWjU1R1dOZStoM2tLekFvR0JBTjlZKzR1Y0lTV2d1dUE1c0JaOQpLZmZPVEFvTUFNN2FsWktSMmprZ1dXOWx1Q3JGZEE4NDk4RFVjdXVTd1lLRmdVRW4zOXh3SDUzeWhNUW1YNXhkCmlJRHF2anozY2h5VW44Y1lTRDNUWjlaU0NEek9pNEIzSEJ2WVZzT1hMLzhiRG5RWVRlV3N2Nms3RS9URlBHMDQKaEN1U1AyT1gvenNiOTFDV0NQQXlVME52Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      -----END PRIVATE KEY-----

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
